-- Dashboard invite-only access list (SOM-54 / SOM-65).
-- Separate from public."Whitelist". Waitlist signup does not grant dashboard access.

create table if not exists public.dashboard_invites (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'approved',
  invited_at timestamptz not null default now(),
  notes text,
  constraint dashboard_invites_email_unique unique (email),
  constraint dashboard_invites_status_check check (status in ('approved', 'revoked')),
  constraint dashboard_invites_notes_length check (notes is null or char_length(notes) <= 2000)
);

create unique index if not exists dashboard_invites_email_lower_idx
  on public.dashboard_invites (lower(trim(email)));

alter table public.dashboard_invites enable row level security;

-- No anon/authenticated access. Edge Functions use the service role key.
revoke all on table public.dashboard_invites from anon, authenticated;

comment on table public.dashboard_invites is
  'Invite-only dashboard access list. Manual founder/admin provisioning only.';
