create extension if not exists pgcrypto;

create table if not exists public."Whitelist" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  role text not null,
  message text,
  constraint "Whitelist_email_unique" unique (email),
  constraint "Whitelist_role_check" check (role in ('Learner', 'Company', 'Investor / Partner')),
  constraint "Whitelist_name_length" check (char_length(trim(name)) between 1 and 160),
  constraint "Whitelist_message_length" check (message is null or char_length(message) <= 2000)
);

do $$
begin
  if exists (
    select 1
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'Whitelist'
      and a.attname = 'id'
      and not a.attisdropped
      and a.attidentity = ''
      and not exists (
        select 1
        from pg_attrdef d
        where d.adrelid = a.attrelid
          and d.adnum = a.attnum
      )
  ) then
    alter table public."Whitelist"
      alter column id add generated by default as identity;
  end if;
end $$;

create unique index if not exists "Whitelist_email_unique_idx"
  on public."Whitelist" (email);

alter table public."Whitelist" enable row level security;

grant insert on table public."Whitelist" to anon;

drop policy if exists "Anyone can join waitlist" on public."Whitelist";

create policy "Anyone can join waitlist"
  on public."Whitelist"
  for insert
  to anon
  with check (true);
