import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dashboardRoot = join(__dirname, '..');
const outputPath = join(dashboardRoot, 'src/environments/environment.generated.ts');

function loadDotEnv(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  return readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .reduce((env, line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        return env;
      }

      const separatorIndex = trimmed.indexOf('=');
      if (separatorIndex === -1) {
        return env;
      }

      const key = trimmed.slice(0, separatorIndex).trim();
      const value = trimmed.slice(separatorIndex + 1).trim();
      env[key] = value;
      return env;
    }, {});
}

function readEnv(name, fallback = '') {
  return process.env[name] ?? dotEnv[name] ?? fallback;
}

function readBoolean(name, fallback = false) {
  const value = readEnv(name, fallback ? 'true' : 'false').toLowerCase();
  return value === 'true' || value === '1';
}

const dotEnv = {
  ...loadDotEnv(join(dashboardRoot, '.env.local')),
  ...loadDotEnv(join(dashboardRoot, '.env')),
};

const appUrl = readEnv('DASHBOARD_APP_URL', 'http://localhost:4200').replace(/\/$/, '');
const supabaseUrl = readEnv('DASHBOARD_SUPABASE_URL', 'https://qufrbaxgiknacfsjfqoy.supabase.co');
const publishableKey = readEnv('DASHBOARD_SUPABASE_PUBLISHABLE_KEY', '');
const authEnabled = readBoolean('DASHBOARD_AUTH_ENABLED', Boolean(publishableKey));
const googleEnabled = readBoolean('DASHBOARD_GOOGLE_ENABLED', authEnabled);
const redirectUrl = readEnv('DASHBOARD_AUTH_REDIRECT_URL', `${appUrl}/dashboard/tasks`);
const callbackUrl = readEnv('DASHBOARD_AUTH_CALLBACK_URL', `${appUrl}/auth/callback`);

const contents = `// Generated by scripts/generate-env.mjs. Do not edit manually.
export const generatedDashboardEnv = {
  supabase: {
    url: ${JSON.stringify(supabaseUrl)},
    publishableKey: ${JSON.stringify(publishableKey)},
  },
  auth: {
    enabled: ${authEnabled},
    redirectUrl: ${JSON.stringify(redirectUrl)},
    callbackUrl: ${JSON.stringify(callbackUrl)},
  },
  google: {
    enabled: ${googleEnabled},
  },
} as const;
`;

writeFileSync(outputPath, contents, 'utf8');
console.log(`Generated ${outputPath}`);
