// Generated by scripts/generate-env.mjs. Do not edit manually.
export const generatedDashboardEnv = {
  supabase: {
    url: "https://qufrbaxgiknacfsjfqoy.supabase.co",
    publishableKey: "",
  },
  auth: {
    enabled: false,
    redirectUrl: "http://localhost:4200/dashboard/tasks",
    callbackUrl: "http://localhost:4200/auth/callback",
    inviteGateEnabled: false,
  },
  google: {
    enabled: false,
  },
} as const;
